### ISSUE TITLE
Insecure CORS feature.

### ISSUE THREAD

**Issue by dtelaroli** [marcioferlan/vraptor4js-plugin#2]
The CORS feature of this plugin is very insecure, because opens the application to cross-domain sharing to *, this is a severe vulnerability to the most cases.
I think that this feature should be moved to other plugin and added feature to configure the sharing way, like [this CORS filter](http://software.dzhuvinov.com/cors-filter-configuration.html)

That's way, this plugin can be used by who does not want to share resources with others domains.
I think that each VRaptor Plugin should have just one feature or similar features.

**Comment by marcioferlan** [comment]
Since version 1.5.0-SNAPSHOT, you can customize CORS headers via <context-param> in web.xml.
See https://github.com/marcioferlan/vraptor4js-plugin#cors-support
